### ISSUE TITLE
Price Range

### ISSUE THREAD

**Issue by james-psd** [colindaniels/eBay-sold-items-documentation#1]
I can't seem to figure out how to specify a minimum price value for a search.  I am assuming it would be an aspect in the API call but I can't seem to figure out the proper name and value for it.  Help would be much appreciated!

**Comment by james-psd** [comment]
Finally found it by looking through a bunch of eBay html right after posting lol - it is _udlo and _udhi for low and high limits for price range.

**Comment by colindaniels** [comment]
I'll be releasing an easier way to sort by min and max price using the actual values "min_price" and "max_price" instead of _udlo and _udhi to make it easier for developers.
